### ISSUE TITLE
database.init.2.0.sql missing

### ISSUE THREAD

**Issue by wterpstra** [cbfrank/AspNet.Identity.EntityFramework#1]
Your documentation is referencing the database.init.2.0.sql file but i can't find it in the repository. I'd really like to try this out!

**Comment by HaroonSaid** [comment]
You maybe interested in the following http://stackoverflow.com/questions/19940014/asp-net-identity-with-ef-database-first-mvc5/ if you are just want to use the tables in your own database, with DB First approach.
